# Generated by Django 4.2.5 on 2023-09-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('es_disenador', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisigner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.person')),
                ('tipo_disenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tipodisigner')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_solicitud', models.CharField(choices=[('invitado', 'Invitado'), ('registrado', 'Registrado')], default='invitado', max_length=10)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.person')),
                ('guest_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.invitado')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_remitente', models.CharField(max_length=255)),
                ('correo_electronico_remitente', models.CharField(max_length=255)),
                ('asunto', models.CharField(max_length=255)),
                ('contenido_mensaje', models.TextField()),
                ('fecha_hora_envio', models.DateTimeField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagenes', models.TextField()),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.designer')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_hora_creacion', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.person')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.designer')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='disenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.designer'),
        ),
    ]
