# Generated by Django 4.2.5 on 2023-09-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_estado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.estado'),
        ),
    ]
