# Generated by Django 4.2.5 on 2023-09-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_person_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='tipo_solicitud',
        ),
    ]
